### ISSUE TITLE
Separate task

### ISSUE THREAD

**Issue by IanMayo** [debrief/ppt_renderer#26]
I have a folder of images (attached).

I need the images renamed, so they contain a date. The date should be in this format:

yyyymmdd_hhmmss.jpg

The first image needs to be at 19951212_093600

Then each image needs to be 20 seconds later. There are 215 images, so the last image will be about an hour after the first one.

I also require a less dense version of the data.  So, we only rename every 5th file, and they're 1 minute 40 seconds apart.  So, we have fewer images, but they still cover the same time period.

The output of the task will be two zip-files of images - one detailed, the other less detailed.  The first file will be named . `19951212_093600.jpg` . The last image will be named _something like_ `19951212_103420.jpg`

[honolulu engagment.zip](https://github.com/debrief/ppt_renderer/files/2162860/honolulu.engagment.zip)

**Comment by purvil12c** [comment]
[detailed.zip](https://github.com/debrief/ppt_renderer/files/2165563/detailed.zip)
Here is the detailed zip file containing the renamed files (no skipping)

**Comment by purvil12c** [comment]
[densed.zip](https://github.com/debrief/ppt_renderer/files/2165568/densed.zip)
Here is the dense zip file containing the renamed files (contains every 5th file)

**Comment by purvil12c** [comment]
[dense_labeled.zip](https://github.com/debrief/ppt_renderer/files/2165726/dense_labeled.zip)
Renamed files with labels on the image

**Comment by purvil12c** [comment]
[detailed_labeled.zip](https://github.com/debrief/ppt_renderer/files/2165732/detailed_labeled.zip)
Renamed detailed files with labels on the image

**Comment by purvil12c** [comment]
[detailed_black_label.zip](https://github.com/debrief/ppt_renderer/files/2165765/detailed_black_label.zip)
detailed with black labels on the image

**Comment by purvil12c** [comment]
[dense_black_label.zip](https://github.com/debrief/ppt_renderer/files/2165768/dense_black_label.zip)
dense with black labels on the image

**Comment by IanMayo** [comment]
Done.
