### ISSUE TITLE
Show scrolling/appearing diary entries

### ISSUE THREAD

**Issue by IanMayo** [debrief/ppt_renderer#27]
We have observers that watch the wargames, and capture what is happening.  The diary is called a _narrative_, and each observation is called an _entry_.

We'd like these messages to appear in the export.  I've created two test files that include narrative data, in the file-level extensions object.

I'd appreciate you using a trick like the time-box to show these.  But, it will have to be a larger box, and it doesn't appear on a regular interval.  

Please create a new text box on the slide, called "narrative".  We'll duplicate that.

IIRC, the times are specified in milliseconds.  If I've done my maths right, the elapsed value for each Entry is in millis from the start of the simulation run.

If it's better to provide them in elapsed millis since the previous one, I can change it to doing that.

**Comment by purvil12c** [comment]
Can you provide me a sample file that contains such a narrative?

**Comment by IanMayo** [comment]
Hmm, didn't I put it into tracks folder in master branch?

**Comment by purvil12c** [comment]
Okay. Got it.

**Comment by IanMayo** [comment]
Done.
