### ISSUE TITLE
Insert set of coordinates for animation

### ISSUE THREAD

**Issue by IanMayo** [debrief/ppt_renderer#5]
Here are two sets of coordinates.  Experiment with inserting them.

The outer rectangle is 800 wide by 600 tall.

These coordinates will have to be scaled to match the size of the rectangle that will contain them.

Here are the coordinates for the path.
A:  100,100  200,100, 300,200 450,300 400,250 350,200
B:  300,300 250,250 200,250 150,150 130,120 140,150 160,140

** UPDATE ** . I've attached a file containing coordinates to be used, please.

Seeing this PPT running will be a Huge Milestone.  I'll be excited to show it to my users.

**Note:** we can move the coordinates into a structured format, if you like.  You could wrap them in XML, if you wish.  

** Note 2:** [here](https://docs.google.com/spreadsheets/d/16REsKJrcSzH7X77pkgKQP8FS5F3vJIEgyF3LCh5rK8Q/edit#gid=0) is a spreadsheet that includes the transforms necessary to move from Debrief screen coordinates to PowerPoint coordinates

## Steps:
* [x] retrieve the size of the whole presentation (presentation.xml)
* [x] retrieve the size of the rectangle
* [x] use the coordinate transform function to get the rectangle TL & BR in 0..1 animation units (see below)
* [x] Use the new TL & BR to get the origin and dimensions of the rectangle
* [x] Use the origin and dimensions to calculate the screen coords (from GPX) in animation units

## rectangle coords in animation dimensions
```
TL =  coordinateTransformation(mapX, mapY, mapCX, mapCY, 0, 0, 1, 1)
BR = coordinateTransformation(mapX + mapCX, mapY + mapCY, mapCX, mapCY, 0, 0, 1, 1)
```
## rectangle represented as animated target values
```
animX = TL.x
animY = TL.y
animCX = BR.x - TL.x
animCY = BT.y - TL.y
```

Now loop through coordinates with:
`(x,y) = coordinateTransform(x, y, dimensionWidth, dimensionHeight, animX, animY, animCX, animCY)
`

**Comment by IanMayo** [comment]
Sample set of coordinates, plus the times of each step.

[times_and_coordinates.txt](https://github.com/debrief/ppt_renderer/files/2102266/times_and_coordinates.txt)

**Comment by IanMayo** [comment]
Ok, I've exported them using the GPX standard.  It *should* be easier for you to parse & process this data in XML format.

Note: the lat/lon values aren't degrees on the world. They x and y screen coordinates that we will be using.

**Comment by purvil12c** [comment]
For references: http://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_animMotion_topic_ID0EFMLHB.html

**Comment by IanMayo** [comment]
New requests:
* [x] remove the acceleration at the start/end (`accel` and `decel`)
* [x] give them a longer duration (10 seconds, instead of 2 seconds)
* [x] ensure the second animated path has valid ids (it's currently duplicating 5 and 6)

**Comment by IanMayo** [comment]
Scaling not done. Pushed to #22
